name: Build Image and Push

on:
  push:
    branches:
      - main
      - 'release/**'

env:
  IMAGE_NAME: angular-pokedex 
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      -  name: Prepare repository
         uses: actions/checkout@v3

      - name: Get version number
        id: version
        run: |
          ls -la
          npm --help
          app_version=$(npm run version:app --silent)
          echo "APP_VERSION=$app_version" >> $GITHUB_ENV

      - name: Determine Tag
        id: tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "RELEASE_TAG=stable" >> $GITHUB_ENV
            echo "MAIN_TAG=v$APP_VERSION" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == refs/heads/release/* ]]; then
            echo "RELEASE_TAG=release_$APP_VERSION" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=unknown" >> $GITHUB_ENV
          fi

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:${{ steps.tag.outputs.RELEASE_TAG }}, ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:latest

      - name: Tag for Main
        if: startsWith(github.ref, 'refs/heads/main')
        run: docker tag ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:${{ steps.tag.outputs.RELEASE_TAG }} ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:${{ steps.tag.outputs.MAIN_TAG }}
      
      - name: Push Main tags
        if: startsWith(github.ref, 'refs/heads/main')
        run: docker push ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:${{ steps.tag.outputs.RELEASE_TAG }} && docker push ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:${{ steps.tag.outputs.MAIN_TAG }} && docker push ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:stable