name: Build Image and Push
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - release/**

env:

  IMAGE_NAME: angular-pokedex 
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build
    
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:v0.0.2, ${{env.REGISTRY}}/thebluemax/${{env.IMAGE_NAME}}:latest
