name: Build Image and Push
on:
  push:
    branches:
      - develop
    tags:
      - v*
  pull_request:
    branches:
      - release/**

env:

  IMAGE_NAME: angular-pokedex 
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build AND PUSH
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}/${{ github.actor }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{env.REGISTRY}}/${{ github.actor }}/${{env.IMAGE_NAME}}:v0.0.2, ${{env.REGISTRY}}/${{ github.actor }}/${{env.IMAGE_NAME}}:latest
