# This is a basic workflow that is manually triggered

name: Manual Deploy workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Deploy to production'
        # Default value if no value is explicitly provided
        default: 'production'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  deploy_prod:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.PRIV_KEY_F35 }}" > ~/.ssh/id_rsa
        ssh-keyscan -H 51.210.108.192 > ~/.ssh/known_hosts
    - name: pull image
      run: ssh -i ~/.ssh/id_rsa  duser@51.210.108.192 docker compose -f prod02-stack/prod02-stack.yml pull pokedex
    - name: update service
      run: ssh -i ~/.ssh/id_rsa  duser@51.210.108.192 docker service update prod02_pokedex
