name: Create release

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Type of version to release'
        default: 'patch'
        required: true
        type: string

jobs:
  version_release:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        ref: develop

    - name: dependecies
      run: npm ci
        
    - name: Get old version
      run: |
        version_value=$(npm run version:app)
        echo "OLD_VERSION_APP=$version_value" >> $GITHUB_ENV
    -  name: update version number
       run: |
        npm version ${{ github.event.inputs.name }}
    - name: Get new version
      run: |
        version_value=$(npm run version:app)
        echo "NEW_VERSION_APP=$version_value" >> $GITHUB_EN
    - name: update version
      run: |
        npm version ${{ github.event.inputs.name }}
        git add .
        git checkout -b release/${NEW_VERSION_APP}
        git commit -m "${OLD_VERSION_APP} => ${NEW_VERSION_APP}"
        git push 
    - name: Create and push tag
      run: |
          git tag -a ${NEW_VERSION_APP} -m "Release ${NEW_VERSION_APP}"
          git push origin ${NEW_VERSION_APP}