N# This is a basic workflow that is manually triggered

name: Manual version update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to release'
        # Default value if no value is explicitly provided
        default: 'patch'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

jobs:
  version_release:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        ref: develop

    - name: dependecies
      run: npm ci
        
    - name: Get old version
      run: |
        version_value=$(npm run version:app)
        echo "OLD_VERSION_APP=$version_value" >> $GITHUB_ENV
    -  name: update version number
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        npm version ${{ github.event.inputs.name }}
    - name: Get new version
      run: |
        version_value=$(npm run version:app)
        echo "NEW_VERSION_APP=$version_value" >> $GITHUB_EN
    - name: update version
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        git add .
        git commit -m "from ${OLD_VERSION_APP} => ${NEW_VERSION_APP}
        git checkout -b release/${NEW_VERSION_APP}
        npm version ${{ github.event.inputs.name }}

        git push 
